server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.31.100:3306/rbac
    username: root
    password: root
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.bruce.rbac.entity.**

logging:
  level:
    com.bruce.rbac.mapper: debug
